# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=200, unique=True)),
                ('p_type', models.IntegerField(default=0)),
                ('p_email', models.EmailField(max_length=254)),
                ('p_hours_per_week', models.IntegerField(default=0)),
                ('p_signed_hours', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_area',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='p_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.Subject_area'),
        ),
    ]
